### ISSUE TITLE
ubik has only one base in quick defend-and-control

### ISSUE THREAD

**Issue by TheAssassin** [blue-nebula/maps#3]
The `quick` mutator currently causes the map to have just one base. There is no good reason for this, as this could be achieved through the `king` mutator. We suspect that this is a map setting.

CC @voidanix

**Comment by voidanix** [comment]
Could you try [this version](https://cloud.keyedlimepie.org/s/qjkTBWxPSQrKKJB/download/ubik.mpz) and confirm it fixes the issue for you too?

**Comment by TheAssassin** [comment]
Apparently fixes the issue. Please file a PR.

By the way, if you send maps to other people, please send all three/four files. And if you want to upload them here, all you need to do is zip them.
